version: "3.7"

services:
  api:
    image: spring-boilerplate:${APPLICATION_VERSION}
    container_name: numble-server-v2
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TOKEN_VALIDITY_HOURS=${JWT_ACCESS_TOKEN_VALIDITY_HOURS}
      - JWT_REFRESH_TOKEN_VALIDITY_HOURS=${JWT_REFRESH_TOKEN_VALIDITY_HOURS}