server:
  port: 8080
  profiles:
    active: local

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        highlight: true
        format_sql: true
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    username: SA
    password:
    initialization-mode: always
  security:
    user:
      name: user
      password: password

config:
  jwt:
    secret: plzgivemesomepizzaandcoffee
    access-token-validity-in-hours: 24
    refresh-token-validity-in-hours: 48