server:
  port: ${APP_PORT}
  profiles:
    active: prod

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    user:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_USER_PASSWORD}

config:
  jwt:
    secret: ${JWT_SECRET}
    access-token-validity-in-hours: ${JWT_ACCESS_TOKEN_VALIDITY_HOURS}
    refresh-token-validity-in-hours: ${JWT_REFRESH_TOKEN_VALIDITY_HOURS}