spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    open-in-view: false
  error:
    include-exception: false
    include-message: always
    inclue-stacktrace: on_param
    whitelabel:
      enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB